LINK.o=$(LINK.cc) # Use c++ link rule by default instead of c link rule
CXXFLAGS=-std=c++14 -g -O3 -fno-exceptions -fno-rtti

mod_vs_increment_and_test: mod_vs_increment_and_test.o

clean:
	$(RM) *.o mod_vs_increment_and_test
