[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["Doug Richardson <doug@rekt.email>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
