apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-app
  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello
        image: dougrichardson/hello:1.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
    name: hello-service
spec:
    # selector app must match app label in pod.yaml
    type: LoadBalancer
    selector:
        app: hello-app
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80


