apiVersion: v1
kind: Pod
metadata:
    name: hello-pod
    labels:
        app: hello
spec:
    containers:
        - name: hello-container
          image: nginx
          command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']

