apiVersion: v1
kind: Pod
metadata:
    name: hello-pod
    labels:
        app: hello-app
spec:
    containers:
        - name: hello-container
          image: dougrichardson/hello:1.0
---
apiVersion: v1
kind: Service
metadata:
    name: hello-service
spec:
    # selector app must match app label in pod.yaml
    type: NodePort
    selector:
        app: hello-app
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80

